### PR TITLE
support mutable-content for ios

### PR DESCRIPTION
**Pull request by azihsoyn**
this PR resolve https://github.com/mercari/gaurun/issues/53

### CODE REVIEW

**Comment by cubicdaiya** [comment]
Could you log this by [`LogPush()`](https://github.com/mercari/gaurun/blob/master/gaurun/log.go#L92)?

**Comment by azihsoyn** [comment]
Thanks for review!
Is this ok? @cubicdaiya

**Comment by cubicdaiya** [comment]
@azihsoyn Oh, sorry. It was one I forgot to say. Please update [SPEC.md](https://github.com/mercari/gaurun/blob/master/SPEC.md#post-push).

**Comment by cubicdaiya** [comment]
Merged. Thanks.

**Comment by azihsoyn** [comment]
Thank you for merging!

**Pull request merged**
