### PR TITLE
optimize: simplified sendResponse().

### PR DESCRIPTION
**Pull request by cubicdaiya**
As `ResponseGaurun` is very simple, this might be faster and simpler instead of using `json.Marshal()`.

### CODE REVIEW

**Comment by dshumko** [comment]
i think, it's wrong code. may generate wrong json, when msg include "
see https://play.golang.org/p/dckGU84j6z

**Comment by cubicdaiya** [comment]
Hi @dshumko ,

Thank you for the suggestion. I recognize this change is not good in general. But there is not the `sendResponse(msg)` that includes `"` in Gaurun. And the current `sendResponse(msg)` is tricky and verbose.

**Comment by suguru** [comment]
I think appending strings is faster than fmt.Sprintf.

```
package bench

import (
	"encoding/json"
	"fmt"
	"testing"
)

type Response struct {
	Message string `json:"message"`
}

func BenchmarkMarshal(b *testing.B) {
	msg := "sample message"
	for i := 0; i < b.N; i++ {
		res := Response{Message: msg}
		s, _ := json.Marshal(&res)
		if len(s) == 0 {
			b.Fail()
		}
	}
}

func BenchmarkSprintf(b *testing.B) {
	msg := "sample message"
	for i := 0; i < b.N; i++ {
		s := fmt.Sprintf("{\"message\":\"%s\"}", msg)
		if s == "" {
			b.Fail()
		}
	}
}

func BenchmarkAppend(b *testing.B) {
	msg := "sample message"
	for i := 0; i < b.N; i++ {
		s := "{\"message\":\"" + msg + "\"}"
		if s == "" {
			b.Fail()
		}
	}
}
```

Bench Result
```
testing: warning: no tests to run
PASS
BenchmarkSprintf-8	10000000	       195 ns/op
BenchmarkMarshal-8	 3000000	       440 ns/op
BenchmarkAppend-8 	30000000	        46.0 ns/op
```

**Comment by cubicdaiya** [comment]
@suguru Thank you for the suggestion. It seems to be better than `fmt.Sprintf()`.

**Comment by cubicdaiya** [comment]
Merged #32 instead of this.

**Pull request closed without merging**
