### PR TITLE
implement gcm/fcm notification property

### PR DESCRIPTION
**Pull request by y-tajiri**
add notification field for gcm/fcm

### CODE REVIEW

**Comment by cubicdaiya** [comment]
Hi @y-tajiri,

Thank you for the PR and sorry for late response. (I had taken long vacation around year-end and new-year.)

**Comment by cubicdaiya** [comment]
Why do you use `extend`? It looks to provide the same method as your PR.

https://github.com/mercari/gaurun/blob/master/SPEC.md#post-push

**Comment by y-tajiri** [comment]
GCM provides two types of payload
https://developers.google.com/cloud-messaging/concept-options
I want to use type of payload for 'notification'.

But ExtJSON is setting payload of 'data'.

Gaurun Message
```
{
      [
         {
            "token" : ["yyy"],
            "platform" : 2,
            "message" : "Hello, Android!",
            "collapse_key" : "update",
            "delay_while_idle" : true,
            "time_to_live" : 10,
            "extend" : [{ "key": "url", "val": “val1” }, { "key": "intent", "val": “val2” }],
	    “notification”:[{“key”: “body”, “val”: “great match!”},{“key”: "title”, “value”: "Portugal vs. Denmark"]
        }
    ]
}
```
will be converted to

GCM Message
```
{
  "registration_ids" : [“yyy”],
  “collapse_key”: "update”,
  “delay_while_idle”: true,
  “time_to_live”: 10,
  "data" : {
    "message" : "Hello, Android!",
    “url”: “val1”,
    “intent”: “val2”,
  },
  “notification”: {                <= new nodes
    “body”: “great match!”
    “title”: "Portugal vs. Denmark”
  }
}
```

**Comment by cubicdaiya** [comment]
refs #106

**Pull request closed without merging**
